# Generated by Django 5.1.5 on 2025-09-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_tokenomics_contact_telegram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokenomics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('percentage', models.FloatField(help_text='Ajratilgan foiz (%)')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
